blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/ayushmaanbhav/Payments-Management-System/wiki
    about: Check our documentation before opening an issue
  - name: Discussions
    url: https://github.com/ayushmaanbhav/Payments-Management-System/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerabilities
    url: https://github.com/ayushmaanbhav/Payments-Management-System/security/advisories/new
    about: Report security vulnerabilities privately
